working_directory = "None"

[env]
TERM = "alacritty"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-e \"cd ~/\""]
program = "nu"

[window]
dynamic_title = true
title = "Alacritty"
