working_directory = "None"

[env]
TERM = "alacritty"
#
[font]
size = 14
normal = { family = "CaskaydiaMono NFM", style = "Medium" }
builtin_box_drawing = false

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal]
shell = { program = "nu", args = ["-e \"cd ~/\""] }

[window]
dynamic_title = true
title = "Alacritty"
