# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = '$all'
format = "$os$username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$haskell$haxe$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$guix_shell$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$container$shell$character"

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"

[memory_usage]
disabled = false

[time]
disabled = true

[username]
disabled = false
show_always = true

[hostname]
disabled = false

[os]
disabled = false
