# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[memory_usage]
disabled = false

[time]
disabled = true

[username]
disabled = false

[hostname]
disabled = false

[os]
disabled = false
