return {
    {
        'nvim-treesitter/nvim-treesitter',
        event = {'BufReadPost', 'BufNewFile'},
        dependencies = {
            {
                'windwp/nvim-ts-autotag',
                config = function() require('nvim-ts-autotag').setup() end,
            },
            {
                'windwp/nvim-autopairs',
                config = function() require('nvim-autopairs').setup() end,
            },
        },
        config = function()
            require 'nvim-treesitter.configs'.setup {
                autotag = { enable = true },
                highlight = { enable = true },
                indent = { enable = true },
                context_commentstring = { enable = true },
                ensure_installed = {
                    "bash",
                    "c",
                    "c_sharp",
                    "cmake",
                    "comment",
                    "cpp",
                    "css",
                    "dockerfile",
                    "git_config",
                    "git_rebase",
                    "gitattributes",
                    "gitcommit",
                    "gitignore",
                    "go",
                    "gomod",
                    "html",
                    "http",
                    "ini",
                    "java",
                    "javascript",
                    "jsdoc",
                    "json",
                    "json5",
                    "jsonc",
                    "lua",
                    "luadoc",
                    "make",
                    "markdown",
                    "markdown_inline",
                    "python",
                    "regex",
                    "rst",
                    "rust",
                    "scss",
                    "sql",
                    "terraform",
                    "toml",
                    "tsx",
                    "typescript",
                    "vim",
                    "vimdoc",
                    "yaml",
                },
            }
        end,
    },
}
